-- V1 — Baseline schema (Flyway adoption, Iteration-3).
--
-- This is a faithful transcription of the schema Hibernate's own DDL generator produces from the
-- current JPA entities (captured via jakarta.persistence schema-generation against PostgreSQL 16).
-- Because it matches the entity metadata exactly, `spring.jpa.hibernate.ddl-auto=validate` boots
-- cleanly against a database created by this script.
--
-- On an ALREADY-POPULATED database (the deployed Neon, built earlier by ddl-auto=update), Flyway
-- is configured with baseline-on-migrate=true / baseline-version=1, so this V1 is marked as the
-- baseline and NEVER re-runs — the existing tables are left untouched. On a FRESH/empty database
-- (a new Vici Neon, the docker dev DB, or the seed profile) Flyway runs this script to build the
-- whole schema. All future schema changes go in V2, V3, … migrations — never ddl-auto again.

-- ── Parent tables (no outgoing FKs) ─────────────────────────────────────────────────────────────

create table students (
    id           bigint       not null,
    name         varchar(255) not null,
    email        varchar(255),
    phone        varchar(255),
    account_id   varchar(255),
    ext_id       varchar(255),
    status       varchar(255) default 'ACTIVE' not null check (status in ('ACTIVE','PAUSED')),
    created_at   timestamp(6),
    synced_at    timestamp(6) not null,
    deleted_at   timestamp(6),
    primary key (id)
);

create table tutors (
    id         bigint       not null,
    name       varchar(255) not null,
    email      varchar(255),
    phone      varchar(255),
    active     boolean      not null,
    synced_at  timestamp(6) not null,
    deleted_at timestamp(6),
    primary key (id)
);

create table services (
    id               bigint       not null,
    name             varchar(255) not null,
    duration_minutes integer,
    category         varchar(255),
    location         varchar(255),
    active           boolean      not null,
    synced_at        timestamp(6) not null,
    deleted_at       timestamp(6),
    primary key (id)
);

create table family_associations (
    account_id       varchar(255) not null,
    name             varchar(255),
    notes            text,
    brevo_company_id varchar(255),
    created_at       timestamp(6) not null,
    updated_at       timestamp(6),
    primary key (account_id)
);

create table alert_student (
    name           varchar(255) not null,
    account_id     varchar(255) not null,
    lapsed_now     boolean      not null,
    lapsed_status  boolean      not null,
    last_checked_at timestamp(6),
    primary key (name)
);

create table app_users (
    id         bigint generated by default as identity,
    username   varchar(255) not null unique,
    password   varchar(255) not null,
    role       varchar(255) not null check (role in ('ADMIN','STAFF','TUTOR')),
    approved   boolean default true not null,
    created_at timestamp(6) not null,
    primary key (id)
);

create table sync_logs (
    id                   bigint generated by default as identity,
    started_at           timestamp(6) not null,
    finished_at          timestamp(6),
    success              boolean not null,
    students_upserted    integer default 0 not null,
    tutors_upserted      integer default 0 not null,
    services_upserted    integer default 0 not null,
    bookings_upserted    integer default 0 not null,
    students_removed     integer default 0 not null,
    tutors_removed       integer default 0 not null,
    services_removed     integer default 0 not null,
    bookings_removed     integer default 0 not null,
    invoices_upserted    integer default 0 not null,
    invoices_removed     integer default 0 not null,
    memberships_upserted integer default 0 not null,
    memberships_removed  integer default 0 not null,
    account_ids_linked   integer default 0 not null,
    ext_ids_linked       integer default 0 not null,
    family_links_linked  integer default 0 not null,
    statuses_updated     integer default 0 not null,
    error_message        text,
    primary key (id)
);

-- ── Child tables (FK to the above) ──────────────────────────────────────────────────────────────

create table bookings (
    id           bigint       not null,
    student_id   bigint       not null,
    tutor_id     bigint,
    service_id   bigint       not null,
    start_time   timestamp(6) not null,
    end_time     timestamp(6),
    status       varchar(255) not null,
    category     varchar(255),
    location     varchar(255),
    cancelled_at timestamp(6),
    synced_at    timestamp(6) not null,
    deleted_at   timestamp(6),
    primary key (id)
);

create table invoices (
    id         bigint not null,
    student_id bigint,
    number     varchar(255),
    status     varchar(255),
    amount     numeric(12,2),
    currency   varchar(255),
    issued_at  timestamp(6),
    synced_at  timestamp(6) not null,
    deleted_at timestamp(6),
    primary key (id)
);

create table memberships (
    id              bigint not null,
    student_id      bigint,
    name            varchar(255),
    active          boolean not null,
    remaining_count integer,
    start_date      timestamp(6),
    end_date        timestamp(6),
    synced_at       timestamp(6) not null,
    deleted_at      timestamp(6),
    primary key (id)
);

-- ── Foreign keys ────────────────────────────────────────────────────────────────────────────────

alter table bookings    add constraint fk_bookings_student    foreign key (student_id) references students;
alter table bookings    add constraint fk_bookings_tutor      foreign key (tutor_id)   references tutors;
alter table bookings    add constraint fk_bookings_service    foreign key (service_id) references services;
alter table invoices    add constraint fk_invoices_student    foreign key (student_id) references students;
alter table memberships add constraint fk_memberships_student foreign key (student_id) references students;
